### ISSUE TITLE
ET-7700

### ISSUE THREAD

**Issue by tcj-lev** [o0shojo0o/ioBroker.epson_ecotank_et_2750#187]
Ich konnte gerade meinen ET-7700 einbinden.
Musste aber etwas am Script basteln, um es dafür anzupassen.
- readPrinterMaintenance habe ich auskommentiert, weil mein Drucker die Seite (und die Daten) nicht liefert
- Waste bei den Tanks ergänzt
- jetzt fehlt mir ncoch das zweite Schwarz - der Drucker hat Black und Photo-Black, aber die Grafiken heißen beide Ink_B.png

Vielleicht kannst du in das Script ja ein paar if oder whens einbauen, um je nach Druckertyp Teile ein und auszublenden

**Comment by o0shojo0o** [comment]
Mach doch ein PR wenn Du das eh schon bei dir Lokal gemacht hast.
